//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardgameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int product_number { get; set; }
        public int basket_id { get; set; }
        public int user_id { get; set; }
        public int boardgame_id { get; set; }
        public int status_id { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual Boardgame Boardgame { get; set; }
    }
}
