//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardgameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boardgame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boardgame()
        {
            this.Basket = new HashSet<Basket>();
            this.PurchaseItem = new HashSet<PurchaseItem>();
            this.Review = new HashSet<Review>();
        }
    
        public string boardgame_name { get; set; }
        public Nullable<int> min_time { get; set; }
        public Nullable<int> max_time { get; set; }
        public Nullable<int> min_players { get; set; }
        public Nullable<int> max_players { get; set; }
        public string cover_path { get; set; }
        public Nullable<int> years { get; set; }
        public string language { get; set; }
        public int boardgame_number { get; set; }
        public int boardgame_cost { get; set; }
        public Nullable<bool> independence { get; set; }
        public string images_paths { get; set; }
        public string preview_description { get; set; }
        public string full_description { get; set; }
        public string boardgame_equipment { get; set; }
        public int boardgame_id { get; set; }
        public Nullable<int> author_id { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<int> complexity_id { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual Complexity Complexity { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItem> PurchaseItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Review { get; set; }
    }
}
