//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardgameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int items_numbers { get; set; }
        public int item_id { get; set; }
        public int purchase_id { get; set; }
        public Nullable<int> boardgame_id { get; set; }
    
        public virtual Boardgame Boardgame { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
