//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardgameStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public string review_content { get; set; }
        public int review_id { get; set; }
        public int boardgame_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual Boardgame Boardgame { get; set; }
        public virtual User User { get; set; }
    }
}
